# IMAGE DE BASE NODEJS EN VERSION LTS
FROM node:8-alpine
# REPERTOIRE DE TRAVAIL
WORKDIR /src
# COPIE LES FICHIERS LOCAUX DANS L'IMAGE
COPY . /src
# INSTALL YARN
RUN yarn install
# COMPILE
RUN ["yarn","next","build"]
# EXPOSE LE CONTAINER SUR LE PORT 3000
EXPOSE 3000
# LANCE LE SERVEUR
CMD ["yarn", "next", "start" ]