version: '3'

services: 
  web:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports: 
      - "8080:3000"
    volumes:
      - .:/src:rw
    environment:
      - NODE_ENV=development